[[news]]
date = "2026-02"
content = "My paper has been accepted by ASPA 2026 conference and received the SCPA 2026 Student Travel Award ðŸŽ‰, see you in Los Angeles then!"

[[news]]
date = "2025-11"
content = "My paper has been accepted by IRSPM 2026 conference, see you in Perth then!"